### DISCUSSION TITLE
Example for node.js

### DISCUSSION THREAD

**Discussion by yoavnativ** [sensedeep/dynamodb-onetable#36] [Q&A] [answered]
Hello, 

I am trying to use the library in node.js project. I didn't see any working examples. Can someone please share a few?

**Comment by mobsense** [comment]
[UPDATE]: there are samples under the ./samples directory. Also checkout the ./tests, they are really readable too.

I don't have any pre-prepared examples (yet), but that is a good idea. I'll add it to our list.

The code snippets in the README should work.

**Comment by mobsense** [comment, marked as answer]
Here is a serverless.yml to create a table with pk and sk attributes. You need to create the table first.

```
resources:
  Resources:
    MyTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: MyTable
        AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
```

Then the schema defines the primary index and each model would defines a pk and sk attribute. Note that when stored, each entity (model) is stored using the same PK and SK. i.e. they are overloaded.

```
const MySchema = {
    indexes: {
        primary: { hash: 'pk', sort: 'sk' },
    },
    models: {
        Account: {
            pk:          { type: String, value: 'account:${name}' },
            sk:          { type: String, value: 'account:' },
            id:          { type: String, uuid: true, validate: /^[0-9A-F]{32}$/i },
            name:        { type: String, required: true },
            status:      { type: String, default: 'active' },
            zip:         { type: String },
        },
        User: {
            pk:          { type: String, value: 'account:${accountName}' },
            sk:          { type: String, value: 'user:${email}' },
            id:          { type: String, required: true },
            accountName: { type: String, required: true },
            email:       { type: String, required: true },
            firstName:   { type: String, required: true },
            lastName:    { type: String, required: true },
        }
    }
}

```

Then in your code, import the libraries.
```
import {Table} from 'dynamodb-onetable'
import DynamoDB from 'aws-sdk/clients/dynamodb'
const client = new DynamoDB.DocumentClient({/* AWS access params */})
```

Then create the Table access object:

```
```javascript
const table = new Table({
    client: client,
    name: 'MyTable',
    schema: MySchema,
})
```

Then you are good to interact with OneTable APIs

```
let Account = table.getModel('Account')

let account = await Account.create({
    id: '8e7bbe6a-4afc-4117-9218-67081afc935b',
    name: 'Acme Airplanes',
})

let acmeUsers = await User.find({accountName: 'Acme Airplanes'})
```

A really helpful tip is to use debug tracing which traces to the console exactly the commands sent to DynamoDB

```
let acmeUsers = await User.find({accountName: 'Acme Airplanes'}, {debug: true})
```
