### DISCUSSION TITLE
Cannot seem to query existing table with indexes

### DISCUSSION THREAD

**Discussion by paambaati** [sensedeep/dynamodb-onetable#62] [Q&A] [answered]
```typescript

const MainSchema = {
  indexes: {
    primary: { hash: 'pk', sort: 'sk' },
    'uid-index': { hash: 'uid', project: 'all' },
  },
  models: {
    Org: {
      pk: { type: String },
      sk: { type: String },
      uid: { type: String, uuid: true }
    },
  },
}

export type User = Entity<typeof MainSchema.models.Org>

const client = new Dynamo({
  client: new DynamoDBClient({
    endpoint: 'http://localhost:8000',
    region: 'us-east-2',
  })
})

const mainTable = new Table({
  client: client,
  name: 'main-dev',
  schema: MainSchema,
  timestamps: false,
  nulls: true,
})

const UserModel: Model<User> = mainTable.getModel('Org')

function get(uid: string) {
  const getResult = await UserModel.get({ uid },
      {
        index: 'uid-index',
        log: true,
      }
    )
   return getResult
}
 ```

```javascript
const result = get('0a50161d-56ec-4f6e-88fc-6c0b84df6575')
console.log(result)
// prints 'undefined' 😭
// also doesn't print the generated query either!
```

This is based on an existing table, that was originally defined in serverless like this —

```yaml
Resources:
  mainTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: main-dev
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: uid
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: uid-index
          KeySchema:
            - AttributeName: uid
              KeyType: HASH
          Projection:
            ProjectionType: ALL
```

Note that there's a GSI on the field `uid`, and named `uid-index`. I'm trying to use the same index in my code, and I've also verified that the `uid` I'm querying actually exists in the table.

What am I doing wrong?
